### ISSUE TITLE
FeatureCodeTest error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ravi5677/gisgraphy#5]
```
testGetLocalizedDescriptionShouldReturnLocalizedDescription(com.gisgraphy.domain
.valueobject.FeatureCodeTest)
 Time elapsed: 0.07 sec  <<< FAILURE!
junit.framework.ComparisonFailure: If no bundle for the specified locale
exists the thread one should be used expected:<[Ville, village, hameau,
Localité]> but was:<[populated place]>
    at junit.framework.Assert.assertEquals(Assert.java:81)
    at
com.gisgraphy.domain.valueobject.FeatureCodeTest.testGetLocalizedDescriptionShou
ldReturnLocalizedDescription(FeatureCodeTest.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at junit.framework.TestCase.runTest(TestCase.java:168)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at
org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76
)
    at junit.framework.TestResult$1.protect(TestResult.java:110)
    at junit.framework.TestResult.runProtected(TestResult.java:128)
    at junit.framework.TestResult.run(TestResult.java:113)
    at junit.framework.TestCase.run(TestCase.java:124)
    at junit.framework.TestSuite.runTest(TestSuite.java:232)
    at junit.framework.TestSuite.run(TestSuite.java:227)
    at
org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
    at
org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
    at
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(Abstra
ctDirectoryTestSuite.java:140)
    at
org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirec
toryTestSuite.java:127)
    at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.jav
a:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at
org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBoote
r.java:345)
    at
org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1009)

```

Original issue reported on code.google.com by `maxim.se...@gmail.com` on 18 Nov 2009 at 1:54

**Comment by GoogleCodeExporter** [comment]
```
can you update and retest. do you use the command 'mvn clean test' or in an ide
(eclipse) ? what is your locale?

thx
```

Original comment by `davidmasclet@gmail.com` on 18 Nov 2009 at 5:13

**Comment by GoogleCodeExporter** [comment]
```
retested - the same error

i use shell: mvn clean test

$ echo $LANG
en_US.UTF-8
```

Original comment by `maxim.se...@gmail.com` on 18 Nov 2009 at 5:23

**Comment by GoogleCodeExporter** [comment]
```
ok i have check the test, the test run correctly on my server because my locale 
is
french and yours is en

i have to recode the test to be locale independant
```

Original comment by `davidmasclet@gmail.com` on 18 Nov 2009 at 8:09
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `davidmasclet@gmail.com` on 19 Nov 2009 at 6:35
- Added labels: **affects_version-2.0beta**

**Comment by GoogleCodeExporter** [comment]
```
fix in svn commit 537
```

Original comment by `davidmasclet@gmail.com` on 19 Nov 2009 at 10:38
- Changed state: **Fixed**
- Added labels: **fix_version-2.0**

**Comment by GoogleCodeExporter** [comment]
```
fixed!

Tests run: 768, Failures: 0, Errors: 0, Skipped: 0

[INFO] [dbunit:operation {execution: test}]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL

```

Original comment by `maxim.se...@gmail.com` on 19 Nov 2009 at 11:06
