### ISSUE TITLE
can't run unit tests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ravi5677/gisgraphy#6]
```
What steps will reproduce the problem?
1. svn co gidgraphy
2. mvn eclipse:eclipse
3. ./tests.sh

What is the expected output? What do you see instead?
all tests OK
-> java heap space

INFO] [aspectj:compile {execution: default}]
[ERROR] ABORT
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Java heap space
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.OutOfMemoryError: Java heap space


What version of the product are you using? On what operating system?
last svn co
on mac os 10.6.2

Please provide any additional information below.
david, aide moi

```

Original issue reported on code.google.com by `jp.caru...@gmail.com` on 20 Nov 2009 at 7:29

**Comment by GoogleCodeExporter** [comment]
```
sorry, truncated stack trace, here comes the full one :

[INFO] [aspectj:compile {execution: default}]
[ERROR] ABORT
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Java heap space
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.OutOfMemoryError: Java heap space
    at java.lang.String.toCharArray(String.java:2725)
    at
org.codehaus.plexus.util.xml.pull.MXParser.defineEntityReplacementText(MXParser.
java:573)
    at org.apache.maven.model.io.xpp3.MavenXpp3Reader.read(MavenXpp3Reader.java:4375)
    at
org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjec
tBuilder.java:1588)
    at
org.apache.maven.project.DefaultMavenProjectBuilder.readModel(DefaultMavenProjec
tBuilder.java:1553)
    at
org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepository(Defa
ultMavenProjectBuilder.java:560)
    at
org.apache.maven.project.DefaultMavenProjectBuilder.buildFromRepository(DefaultM
avenProjectBuilder.java:249)
    at
org.apache.maven.project.artifact.MavenMetadataSource.retrieve(MavenMetadataSour
ce.java:106)
    at
org.apache.maven.artifact.resolver.DefaultArtifactCollector.recurse(DefaultArtif
actCollector.java:380)
    at
org.apache.maven.artifact.resolver.DefaultArtifactCollector.collect(DefaultArtif
actCollector.java:76)
    at
org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(D
efaultArtifactResolver.java:300)
    at
org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(D
efaultArtifactResolver.java:288)
    at
org.apache.maven.plugin.DefaultPluginManager.ensurePluginContainerIsComplete(Def
aultPluginManager.java:770)
    at
org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginMana
ger.java:604)
    at
org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.ja
va:429)
    at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycl
eExecutor.java:558)
    at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(Def
aultLifecycleExecutor.java:499)
    at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycle
Executor.java:478)
    at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures
(DefaultLifecycleExecutor.java:330)
    at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultL
ifecycleExecutor.java:291)
    at
org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExec
utor.java:142)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 minutes 8 seconds
[INFO] Finished at: Fri Nov 20 20:24:25 CET 2009
[INFO] Final Memory: 81M/81M
[INFO] ------------------------------------------------------------------------

```

Original comment by `jp.caru...@gmail.com` on 20 Nov 2009 at 7:32

**Comment by GoogleCodeExporter** [comment]
```
Hi

you must set the MAVEN_OPTS.

export MAVEN_OPTS='-Xmx512m -Xms256m' if you are on linux / mac
or edit environement variable in windows.

i've added this to the test.sh script. (SVN commit 538)


```

Original comment by `davidmasclet@gmail.com` on 21 Nov 2009 at 5:42
- Changed state: **Fixed**
- Added labels: **fix_version-svn538**

**Comment by GoogleCodeExporter** [comment]
```
c'est bien ce que je me disais
ça fonctionne mieux ainsi (bon, j'ai pas de BDD...)
```

Original comment by `jp.caru...@gmail.com` on 21 Nov 2009 at 9:28
